title: Azure Data Blog
description: Landing page técnica sobre Azure Data Platform por Deygerson
baseurl: ""
url: "https://deygerson-mndz.github.io"
theme: null

author:
  name: Deygerson M.
  email: deygerson@gmail.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag
